spring.application.name=it-servicedesk

spring.datasource.url=jdbc:postgresql://localhost:5432/servicedesk
spring.datasource.username=servicedesk
spring.datasource.password=servicedesk

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true